### PR TITLE
Update CSharp.stg

### PR DESCRIPTION
**Pull request by apacha**
Removed CLSCompliant attribute to remove warning from Auto-generated files.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Have you tested it? It's ok?
Also still need you to add yourself to contributors

**Comment by ericvergnaud** [comment]
And there is more than 1 CLSCompliant annotation in this file I believe

**Comment by apacha** [comment]
When removing it manually in the generated code, it works fine, but I haven't tested it when it is freshly generated with the new template.

Will do that later.

**Comment by sharwell** [comment]
Warnings for the use of this attribute only appear if your assembly is missing a `CLSCompliant` attribute. To resolve the warning, add the following line to your **AssemblyInfo.cs** file:

```csharp
[assembly: CLSCompliant(false)]
```

Note that if the generated code is CLS compliant, then the attribute in the generated code could be changed to `[CLSCompliant(true)]`, but in no case should it be removed.

**Comment by apacha** [comment]
I see. What parts of the generated code are not cls compliant? I guess that the code that was generated for me, didn't contain any, so I got this warning. Maybe we should put the solution into the documentation.

**Comment by ericvergnaud** [comment]
The code is now CLSCompliant so those attributes are not necessary.

**Pull request closed without merging**
