### PR TITLE
Wrong property when building for net v4.5.

### LINKED ISSUE #9: [NET45PLUS] Antlr4.Runtime.Atn.ATNState has no definition for Transitions
Got the build error when building with following msbuild properties:

   TargetFrameworkVersion=v4.5;DefineConstants="TRACE;NET35PLUS;NET40PLUS;NET45PLUS"

Misc\RuleDependencyChecker.cs(380,57): error CS1061: 'Antlr4.Runtime.Atn.ATNState' enthält keine Definition für 'Transitions', und es konnte keine Erweiterungsmethode 'Transitions' gefunden werden, die ein erstes Argument vom Typ 'Antlr4.Runtime.Atn.ATNState' akzeptiert (Fehlt eine Using-Direktive oder ein Assemblyverweis?). [antlr4-csharp\Runtime\CSharp\Antlr4.Runtime\Antlr4.Runtime.vs2013.csproj]

TransitionsArray has to be used.

PR in preparation.

Regards,
ViceIce

### PR DESCRIPTION
**Pull request by ViceIce**
Fixes #9.

### CODE REVIEW

**Comment by ericvergnaud** [comment]
Mmm
not sure I agree with this.
What prevents iterating over state.Transitions ?

**Comment by ericvergnaud** [comment]
Actually what is missing is a public Transitions getter property in ATNState

**Comment by ViceIce** [comment]
At [L935](https://github.com/ViceIce/antlr4-csharp/blob/ffc46307b1914c5f41ab763c5f298640f78569a8/runtime/CSharp/Antlr4.Runtime/Misc/RuleDependencyChecker.cs#L935) you find the same loop. But with the `TransitionsArray` property.

**Comment by ericvergnaud** [comment]
I still think that an Iterator on state.transitions would be more effective

**Comment by ViceIce** [comment]
I agree. Then both loops should be changed.

**Comment by ericvergnaud** [comment]
Yes. Can you:
 - sign the contributor's agreement
 - submit the corresponding PR

**Comment by ViceIce** [comment]
Signed. See 4aeae0edf82ad2152ddf992424c2167629330a10

**Comment by ericvergnaud** [comment]
Welcome aboard.
Can you update your PR in line with our discussion?

**Comment by ViceIce** [comment]
Yes. I will do it.

**Comment by ViceIce** [comment]
Done.

**Comment by ericvergnaud** [comment]
Are you sure this compiles?
transitions is internal, so not sure how RuleDependencyChecker can access it.

**Comment by ViceIce** [comment]
Yes. I tested it. Internal mean's visible only in this assembly.

**Pull request merged**
